print('=== List Programs ===')
print('Eps 03 - How Programs and Bytecode')
print('Eps 04 - Variables')
print('Eps 05 - Data Type')
print('Eps 06 - Data Type Casting')
print('Eps 07 - Take input data from the user')
print('Eps 08 - Arithmetic Operations')
print('Eps 09 - Simple Calculation Exercises')
print('Eps 10 - Comparison Operation')
print('Eps 11 - Logical or Boolean Operations')
print('Eps 12 - Comparison and Logic Exercises')
print('Eps 13 - Bitwise Operators')
print('Eps 14 - Assignment Operator')
print('Eps 15 - String Recognition')
print('Eps 16 - String Operations and manipulation (1)')
print('Eps 17 - String Operations and manipulation (2)')
print('Eps 18 - String Format')
print('Eps 19 - String Width and Alignment')
print('Eps 20 - Date and Time (Practice)')
print('Eps 21 - If and Else Statement')
print('Eps 22 - ELIF = Else If Statement')
print('Eps 23 - Simple Calculator')
print('Eps 24 - For Loop')
print('Eps 25 - While Loop')
print('Eps 26 - Continue and Pass')
print('Eps 27 - Break')
print('Eps 28 - Repetition Practice')
print('Eps 29 - List')
print('Eps 30 - List Manipulation')
print('Eps 31 - List Operation')
print('Eps 32 - Copy List')
print('Eps 33 - Nested List')
print('Eps 34 - Deep Copy Nested List')
print('Eps 35 - Looping List and Enumerate')
print('Eps 36 - Exercise List')
print('Eps 37 - Tuples and Set')
print('Eps 38 - Dictionary')
print('Eps 39 - Operation Dictionary')
print('Eps 40 - Looping Dictionary')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')
print('Eps ')